---
name: Bug report
description: Send a bug WinUEFI has that needs to be fixed
title: "[BUG] <title>"
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Thank you for filling out a bug that WinUEFI has! It helps me make the application better. Please be as detailed as possible so that i may consider and review the bug easier.
      I ask that you search all the issues to avoid a duplicate bug. If one exists, please reply if you have anything to add to it.
      Before requesting a bug, please make sure you are using the latest version and that the bug you are requesting is not already fixed in WinUEFI.                       
- type: textarea
  id: bug-and-suggestion-relation
  attributes:
    label: Is your bug related to a suggestion?
    description: Please give some context for this request. Why do you want it to be fixed?
  validations:
    required: true
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is and what needs to be fixed.
  validations:
    required: true
 - type: textarea
   id: alternatives
   label: Describe alternatives you've considered
   description: List any alternatives you might have tried to fix the bug you want.
 - type: checkboxes
   id: agreements
   label: Agreements
   description: Please agree to the following:
   options:
     - label: I have searched for and ensured there isn't already an open issue regarding this.
       required: true
     - label: I have ensured the bug I'm reporting isn't already fixed in the latest supported WinUEFI build.
       required: true
 - type: textarea
   id: other
   attributes:
     label: Other
     description: Add any other context or screenshots about the feature request below.
