---
name: Software Review
description: An Review for Easy UEFI
labels: review
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to rate Easy UEFI! Fill out the following form to your best ability to help us know what we can do better.
- type: textarea
  attributes:
    label: advantages
    description: Please tell us the best advantages from the software.
  validations:
    required: true
    attributes:
    label: cons
    description: Please tell us the most cons about this software.
