name: Add suggestions/enhancements to WinUEFI v2 project

on:
  issues:
    types:
      - opened

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/FreakinSoftMania/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: enhancement, suggestion
          label-operator: OR
