name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.0.2

      # Login against the Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Login against the GitHub registry except on PR
      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-docker
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            docker.io/${{ github.repository }}
            ghcr.io/${{ github.repository }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image (with push)
        id: build-push
        uses: docker/build-push-action@v6
        with:
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/winuefi:${{ steps.meta-docker.outputs.tags }}
            ghcr.io/${{ github.repository }}:${{ steps.meta-docker.outputs.tags }}
            ghcr.io/${{ github.repository }}:latest
          push: ${{ github.event_name != 'pull_request' }}

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Run Docker image
        run: docker run ghcr.io/${{ github.repository }} || exit /b 0
        shell: cmd
